### ISSUE TITLE
Could not decode crash log: Could not decode invalid crash log header

### ISSUE THREAD

**Issue by DanieleRatti** [dangelov/Basic-Symbolicate#1]
I'm always getting this error:

Could not decode crash log: Could not decode invalid crash log header
from the plcrashutil call.

I tried both the crash log as is from Apple review (with all the headers) and also a reduced version with just the content below the "Binary Images:".

What am I wrong with this log?

**Comment by dangelov** [comment]
I haven't encountered that error yet, but it's not part of "basic-symbolicate". This project uses "plcrashutil" behind the scenes, which is outputting that error. Does this answer here help you? http://stackoverflow.com/questions/4398247/decoding-protobuf-data-from-plcrashreporter

I'd suggest Googling the issue.
